### ISSUE TITLE
How to match the original docs and the results?

### ISSUE THREAD

**Issue by ChenSuL** [yangliuy/LDAGibbsSampling#2]
Hello, there's one point that I don't understand. How to match the original docs and the results?
What is the order in which the documents is processed?
Thank you!

**Comment by yangliuy** [comment]
Thank you for your question.

You can figure out the order of the document in readDocs function in https://github.com/yangliuy/LDAGibbsSampling/blob/master/src/liuyang/nlp/lda/main/Documents.java
